# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ParcellNumbering
                                 A QGIS plugin
 Numbering parcells within forest quarter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-02-03
        copyright            : (C) 2024 by Rudenko V.M.
        email                : v.m.rudenko@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Rudenko V.M.'
__date__ = '2024-02-03'
__copyright__ = '(C) 2024 by Rudenko V.M.'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ParcellNumbering class from file ParcellNumbering.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ParcellNumbering import ParcellNumberingPlugin
    return ParcellNumberingPlugin()
